In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from utils.Preprocessing import *
from utils.Plot import *
from utils.constants import *

In [7]:
# np.savez("Train_train.npz", train_dataX, train_label)
# np.savez("Test_Exp_test.npz", exp_dataX, exp_label)

train_data = np.load("Train_train.npz")
test_data = np.load("Test_Exp_test.npz")
Xtr, ytr = train_data['arr_0'], train_data['arr_1']
Xte, yte = test_data['arr_0'] , test_data['arr_1']

Xtr = Xtr.reshape((Xtr.shape[0],-1))
Xte = Xte.reshape((Xte.shape[0],-1))

In [8]:
Xtr.shape, Xte.shape

((8001, 1152), (413, 1152))

In [12]:
scaler = StandardScaler()
scaler.fit(Xtr)

Xtr_norm = scaler.transform(Xtr)
Xte_norm = scaler.transform(Xte)

In [13]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(Xtr_norm, ytr)

y_pred = classifier.predict(Xte_norm)

In [14]:
print(confusion_matrix(yte, y_pred))
print(classification_report(yte, y_pred))

[[ 3  0  0  0  0  0  0  0  0  0  0  0  1 12  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0  3  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  4  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  5  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  0  0  0  1  2  1  1  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  3  0  0  2  0]
 [ 0  0  0  2  0  0 14  1  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  1  3  0  0  0  0 28  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  3  0  0  0  0  1  1  0  1]
 [ 0  0  0  0  0  0  0  4  0  0  0  0  2  2  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0  1  0  0  2  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  1  1  0  0  2  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 96  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 63  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 21 23  0  0]
 [ 1  0  0  0  1  0  0  1  0  0  0  0  6  3  3 21  0]
 [ 0  0  0  0  0  0  3  1  0  0  1  0  1  0  0  0  8]]
              precision    recall  f1-score   support

           1       0.43   

D:\anaconda\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
