In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from utils.Plot import heatmap
from utils.constants import TARGET_NAMES

import numpy as np

train_data = np.load("Train_train.npz")
test_data = np.load("Test_Exp_test.npz")
Xtr, ytr = train_data['arr_0'], train_data['arr_1']
Xte, yte = test_data['arr_0'] , test_data['arr_1']

Xtr = Xtr.reshape((Xtr.shape[0],-1))
Xte = Xte.reshape((Xte.shape[0],-1))

In [6]:
scaler = StandardScaler()
scaler.fit(Xtr)

Xtr_norm = scaler.transform(Xtr)
Xte_norm = scaler.transform(Xte)

In [ ]:
clf = SVC(gamma='auto')
clf.fit(Xtr_norm, Xte_norm)

In [8]:
y_pred = clf.predict(Xte_norm)

In [17]:
# heatmap(yte, y_pred, 17, "SVM")

In [18]:
print(confusion_matrix(yte, y_pred))
print(classification_report(yte, y_pred))

[[ 80   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  73   0   0   0   0   0   0   0   0   0   0   0   6   0   0   0]
 [  0   0  40   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  40   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  40   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  39   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 155   0   0   0   0   0   2   0   0   0   0]
 [  0   0   0   0   0   0   0 159   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  40   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  40   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  40   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  40   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 494   1   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0 165   0   0   0]
 [  0 